
development:
  adapter: mysql2
  encoding: utf8
  database: bacteria_growth
  pool: 5
  username: root
  password: "zxc"

production:
  adapter: mysql2
  encoding: utf8
  database: bacteria_growth
  pool: 5
  username: kdbio_rails
  password: "123456"
